[package]
name = "whitespace-stego-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
base64.workspace = true
fernet.workspace = true
thiserror.workspace = true
clap = { version = "4.5.1", features = ["derive"] }

[dev-dependencies]
proptest.workspace = true
criterion.workspace = true
test-case.workspace = true

[[bench]]
name = "performance"
harness = false 