[package]
name = "whitespace-stego-rust"
version = "0.1.0"
edition = "2021"

[lib]
name = "whitespace_stego_rust"
crate-type = ["cdylib", "rlib"]

[dependencies]
pyo3.workspace = true
whitespace-stego-core = { path = "../whitespace-stego-core" }
clap = { version = "4.5", features = ["derive"] }

[dev-dependencies] 