[package]
name = "whitespace-stego-backend"
version = "0.1.0"
edition = "2021"

[lib]
name = "whitespace_stego_backend"
crate-type = ["cdylib", "rlib"]

[dependencies]
pyo3 = { version = "0.20.3", features = ["extension-module"] }
whitespace-stego-core = { path = "../whitespace-stego-core" }

[dev-dependencies]
whitespace-stego-backend = { path = "." } 