/*
 * Auto-generated buffer size configuration
 * Generated by configure_buffer_sizes.sh
 */

#ifndef BUFFER_SIZES_H
#define BUFFER_SIZES_H

// Maximum detected working buffer size
#define MAX_DETECTED_BUFFER_SIZE 4294967295

// Recommended buffer sizes
#define TINY_BUFFER_SIZE 4096
#define SMALL_BUFFER_SIZE 1048576
#define STANDARD_BUFFER_SIZE 16777216
#define LARGE_BUFFER_SIZE 4294967295

// Buffer size validation
#define IS_VALID_BUFFER_SIZE(size) ((size) <= MAX_DETECTED_BUFFER_SIZE)

#endif // BUFFER_SIZES_H
