name: Rust

on:
  push:
    paths:
      - 'rust/whitespace_stego_rs/**'
  pull_request:
    paths:
      - 'rust/whitespace_stego_rs/**'

jobs:
  rust-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: rust/whitespace_stego_rs
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Build
        run: cargo build --release