name: Rust CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  rust:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy
        
    - name: Install Python
      uses: actions/setup-python@v5make
      with:
        python-version: "3.10"
        
    - name: Install maturin
      run: pip install maturin
        
    - name: Build Rust CLI
      run: make rust-cli

    - name: Run Rust tests
      run: make -C rust_backend test
        
    - name: Build and test Python bindings
      run: |
        maturin develop
        pytest tests/test_rs.py 